# Site Settings
title: "Rutva Pandya"
email: your.email@example.com
description: "Software Engineering Student & NLP Researcher"
baseurl: ""
url: "https://rutvapandya.com"

# Use built-in GitHub Pages theme (guaranteed to work)
theme: minima

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins (GitHub Pages compatible only)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Social links
github_username: Rutva-Pandya
linkedin_username: yourprofile
twitter_username: yourhandle

# Navigation
header_pages:
  - about.md

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/