# Site metadata
title: "Rutva Pandya"
email: your.email@example.com
description: "Aspiring Software Engineer & NLP Enthusiast"

# URLs
baseurl: ""                        # no subpath
url: "https://rutvapandya.github.io"  

# Markdown and syntax highlighting
markdown: kramdown
highlighter: rouge

# Theme and plugins
theme: jekyll-theme-minimal-mistakes
minimal_mistakes_skin: dusk        # enables dark/light toggle

plugins:
  - jekyll-feed
  - jekyll-seo-tag
