# _config.yml

# Site metadata
title: "Rutva Pandya"
email: your.email@example.com
description: "Aspiring Software Engineer & NLP Enthusiast"

# URL settings
baseurl: ""                           # no subpath
url: "https://rutvapandya.com"        # your custom domain

# Markdown and syntax highlighting
markdown: kramdown
highlighter: rouge

# Remote theme (Minimal Mistakes)
remote_theme: mmistakes/minimal-mistakes@HEAD

# Plugins to enable
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# (Optional) any Minimal Mistakes config goes here, e.g.:
minimal_mistakes_skin: dusk
