title: "Rutva Pandya"
email: rpandya4@jh.edu
description: "CS Masters Student & NLP Researcher"
baseurl: ""
url: "https://rutvapandya.com"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Social links (update these with your actual usernames)
github_username: Rutva-Pandya
linkedin_username: rutva-pandya
x_username: RutvaPandya8

# Navigation
header_pages:
  - publications.md
  - blog.md

# Author information (properly formatted)
author:
  name: "Rutva Pandya"
  email: "rpandya4@jh.edu"

# Custom CSS
sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - node_modules/
  - "*.tmp"
  - "*.bak"
