title: "Rutva Pandya"
email: your.email@university.edu
description: "CS Masters Student & NLP Researcher"
baseurl: ""
url: "https://rutvapandya.com"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Social links (update these with your actual usernames)
github_username: Rutva-Pandya
linkedin_username: yourprofile

# Navigation
header_pages:
  - index.md
  - about.md
  - publications.md
  - blog.md

# Author information
author:
  name: "Rutva Pandya"
  email: "your.email@university.edu"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - node_modules/
  - "*.tmp"
  - "*.bak"
